#!/usr/bin/env python

#*****************************************************************************
#
# Obfuscate.py
#
#
#
#*****************************************************************************
#
#
# Copyright 2013-2022 Sighthound, Inc.
#
# Licensed under the GNU GPLv3 license found at
# https://www.gnu.org/licenses/gpl-3.0.txt
#
# Alternative licensing available from Sighthound, Inc.
# by emailing opensource@sighthound.com
#
# This file is part of the Sighthound Video project which can be found at
# https://github.com/sighthoundinc/SighthoundVideo
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; using version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02111, USA.
#
#
#*****************************************************************************

import sys, random, base64

"""
## @file
Obfuscation functions based on doing an XOR of an 8bit random sequence over a
string's characters. The sequence is generated by a seeded random.Random, an
16bit (two characters) salt value is used to make the obfuscated result
different and not too easy to guess. This is just for hiding purposes, since the
'secret' key and the method can be dug up easily it should NOT be used for truly
sensitive data!

NOTE: originally used random.WichmannHill, which Python removed in 3.9+; now
uses random.Random instead. Values obfuscated by the old WichmannHill-based
save() cannot be de-obfuscated by this load() (they'll raise ValueError, same
as any other undecodable input) -- callers must treat that as "no cached
value" rather than a hard failure, which is what the one live caller
(BackEndClient.getLoginStatus, for a cached login token) already does.
"""

# the global "secret" for obfuscation
_kSecret = 0xb3ec6759ec8c2328

###############################################################################
def save(text, secret=_kSecret):
    """ Obfuscates a string.

    @param text    The text to obfuscate
    @param secret  The individual secret value to obfuscation, 64bit integer.
    @return        The obfuscated value, as a str. Likely to be different on
                   every call.
    """
    rnd = random.SystemRandom()
    slt = rnd.randint(0, 32767)
    gen = random.Random(secret + slt)
    result = bytes([slt >> 8, slt & 255])
    result += bytes(b ^ gen.getrandbits(8) for b in text.encode('utf-8'))
    return base64.b64encode(result).decode('ascii')


###############################################################################
def load(text, secret=_kSecret):
    """ De-obfuscates a string formerly obfuscated with the save() function.

    @param text        The text to de-obfuscate.
    @param secret      The individual secret value (int64) to obfuscation. Must
                       match what was used for obfuscation before, otherwise
                       only gibberish gets returned.
    @return            The (hopefully) de-obfuscated text.
    @raise ValueError  If the text somehow caused a decoding error.
    """
    try:
        enc = base64.b64decode(text)
        slt = (enc[0] << 8) | enc[1]
        gen = random.Random(secret + slt)
        result = bytes(b ^ gen.getrandbits(8) for b in enc[2:])
        return result.decode('utf-8')
    except:
        raise ValueError(str(sys.exc_info()[1]))


###############################################################################

if __name__ == '__main__':
    print(save(sys.argv[1]))

