#! /usr/local/bin/python

#*****************************************************************************
#
# QueuedDataManagerCloud.py
#     Utility class running as part of camera process,
#     collecting object tracks generated by Sentry/tracker,
#     and submitting them for classification by SIO.
#
#
#*****************************************************************************
#
#
# Copyright 2013-2022 Sighthound, Inc.
#
# Licensed under the GNU GPLv3 license found at
# https://www.gnu.org/licenses/gpl-3.0.txt
#
# Alternative licensing available from Sighthound, Inc.
# by emailing opensource@sighthound.com
#
# This file is part of the Sighthound Video project which can be found at
# https://github.com/sighthoundinc/SighthoundVideo
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; using version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02111, USA.
#
#
#*****************************************************************************


# Python imports...
import sys
import time
import os
import traceback
from datetime import datetime

def _msToFolder(ms):
    """The day folder a thumbnail for `ms` belongs in -- LOCAL date.

    Local, not UTC: a thumbnail is filed under the day the operator saw the
    event, so an evening event does not appear under tomorrow's date.  Changed
    2026-09-06 at the owner's request.

    This MATCHES the clip day folder, which has always been local.  Clips are
    filed by StreamReader._registerRemuxSegment, which slices the date out of
    the segment filename ffmpeg's `-f segment` muxer wrote with LOCAL strftime
    -- no timezone conversion in Python at all.  Verified over 4,000 clipdb
    rows: of the 727 whose local and UTC dates differ, 727 are under the local
    name and none under UTC.

    So this change did not separate thumbnails from their clips, it reunited
    them: thumbnails were the only thing here filed by UTC, which put an
    evening thumbnail one day ahead of the clip it belongs to.

    (StreamReader._roll_clip DOES build a UTC folder name, but that is the
    re-encode fallback, not the live stream-copy path.  Reading it as the live
    path is what produced the wrong conclusion this comment used to carry.)

    Three functions must agree on this and are changed together:
    this one writes the thumbnail, DataManager._msToFolder finds it, and
    DiskCleaner._enumDateFolders deletes it.
    """
    return datetime.fromtimestamp(ms / 1000.0).strftime('%Y-%m-%d')

from PIL import Image
from collections import deque, defaultdict

from .ObjectDetectorClient import ObjectDetectorClientInProcess, \
                                  _kMaxPendingWorkItems as _kClientQueueBound
from .ObjectDetectorClientImageCheck import ObjectDetectorClientImageCheck

# Common 3rd-party imports...

# Local imports...
from . import MessageIds
from appCommon.CommonStrings import kThumbsSubfolder

from svsentry.Sentry import ObjectCollector, loadSentry

# Globals...
from vitaToolbox.image.ImageConversion import convertProcFrameToPIL
from vitaToolbox.ctypesUtils.LoadLibrary import LoadLibrary

loadSentry(LoadLibrary, None)

_kFrameSaveInterval=1000 # distance in ms between frames we save
_kStatsReportInterval=30
_kUnknownType = "unknown"
# Minimum average detector score for a real type to beat accumulated "unknown"
# abstentions in the forced-decision vote (see _summarizeScores).  Sits between
# YOLO's 0.25 detection floor -- low enough to admit the marginal misreads that
# moving foliage produces -- and the 0.5-0.9 that genuine subjects measure on
# this fleet.
_kMinRealTypeScore = 0.5
# Maximum distance from the last Sentry appearance of the object we're willing
# to go before giving up on the track (normally, we'd wait for the cloud reports
# to catch up)
#
# MUST stay above ObjectDetectorClient._kMaxWorkItemAgeMs (5000), which is the
# age at which a queued work item is dropped -- and every drop still publishes a
# result, so that path resolves the object on its own.  Held at 5000 the two
# raced at the same deadline and the winner was a coin flip: measured
# 2026-08-29, nine objects were force-decided to "unknown" milliseconds before
# their real answer landed.  Sitting clear of the drop leaves this as what it is
# meant to be -- the backstop for an answer that never arrives at all, not a
# competitor to the normal path.
_kForceDecisionTimeout=10000

# Post-report attribute refresh: keep sampling person objects with the
# detector after their type vote completes (throttled per object) so a face
# recognized late in the track still reaches the DB via
# msgIdDataUpdateObjectAttrs.  Config-gated; False = legacy behavior.
try:
    from .ImageCheckConfig import loadConfig as _icLoadConfig
    _kFaceTrackUpdates = bool(_icLoadConfig().get("FACE_TRACK_UPDATES", True))
except Exception:
    _kFaceTrackUpdates = True
_kPostReportDetectIntervalMs = 1000

# How an object's detection budget (_maxDetectionEvents) is SPENT over its life.
# The budget is a count, not a schedule: left alone, _requestDetections hands
# every eligible object to the detector on every 500 ms camera tick, so all 8
# samples land in the track's first 3.5 s and the verdict is locked before
# anything arriving later is ever looked at.
#
# That is not a corner case on a busy camera.  Tracks born on foliage get
# adopted by whatever walks into them afterwards.  Measured 2026-09-01 on
# 05_Gate_lr: a car crossed 15:34:56-15:35:03 and stored as 'object' because
# all six tracks covering it were born 6-13 s earlier on an empty scene and had
# spent their budget by 15:34:52; no track was born while the car was on screen.
# Replaying those exact frames through the live detector returns 'car' at
# 0.78-0.93, so the miss was in WHEN we sampled, not in what the model sees.
#
# The first _kFastDetectSamples are taken at the camera's own tick, exactly as
# before; the rest are spaced by _kDetectSpacingMs:
#
#     0  0.5  1.0  1.5   3.5   5.5   7.5   9.5  s after the track is born
#
# Front-loading is not optional.  14.7% of CLASSIFIED tracks fleet-wide live
# under 1.5 s (measured over the 24 h to 2026-09-01), and spacing all eight
# evenly would cut those from four samples to two.  This schedule leaves every
# track shorter than 1.5 s sampled exactly as it is today, while extending
# reach from 3.5 s to 9.5 s.
#
# The cost is reporting latency, and it is real.  readyToReport force-decides
# on detectionEventsCount >= _maxDetectionEvents -- a count -- and 'unknown'
# scores 0.5 against a 0.9 high-confidence bar, so a noise track can never
# decide early; _processDetections then stops reporting at the first undecided
# frame, so a camera's whole event stream waits on the 8th response.  Added p90
# lag measured 14:00-16:00 on 2026-09-01: 05_Gate_lr +5.2s, 08_Pool +3.3s,
# 03_Hill +2.1s, 09_WestTerrace and 12_Ravine_lr under +2s, and ZERO on the
# remaining eleven cameras, whose tracks are too sparse to block each other.
#
# Widening _kDetectSpacingMs buys deeper reach at a proportional cost in that
# lag -- 3000 ms reaches 13.5 s but costs 05_Gate_lr +8.5s -- so do not raise
# it without re-measuring.  Do not reach for _maxDetectionEvents instead: that
# pays the same latency AND multiplies detector load, which the bounded work
# queue in ObjectDetectorClient answers by dropping frames.
# DISABLED (0) on 2026-09-02, the day it went in.  Do NOT raise this until
# _processCloudResults notifies only the objects that were in the work item.
#
# It notifies every object in the frame instead.  That was harmless while every
# object with budget was in every request -- an excluded object had already
# decided, and notifyDetectionCompleted early-returns for those.  Spacing makes
# the request list a strict SUBSET, so an object waiting out its window is still
# notified: it collects a phantom ('unknown', 0.5, 0.5) vote and, worse, a
# detectionEventsCount increment, every time another object keeps the camera
# enqueueing.
#
# The two counters are not the same one.  needsDetection gates on
# detectionsRequested (real requests) but readyToReport force-decides on
# detectionEventsCount >= _maxDetectionEvents, which only the phantoms inflate.
# At 500 ms ticks a 2000 ms spacing accrues ~4 phantoms per gap, so on a busy
# camera an object is force-decided at '8 events' having genuinely been sampled
# 2-4 times and reaching ~2-3 s into the track -- against 8 real samples reaching
# 3.5 s with this off.  Spacing is therefore a REGRESSION until that is fixed,
# worst exactly where it was meant to help: 05_Gate_lr carries 6+ concurrent
# tracks.  Damage scales with how busy the camera is.
#
# The schedule below is what this buys once the phantom votes stop, and it was
# measured as sound in isolation: 0 0.5 1.0 1.5 3.5 5.5 7.5 9.5 s at 2000, which
# reaches the 9.35-14.19 s window a real car occupied on 05_Gate_lr while leaving
# every track shorter than 1.5 s sampled exactly as it is today.
_kFastDetectSamples = 4
try:
    _kDetectSpacingMs = int(_icLoadConfig().get("DETECT_SPACING_MS", 0))
except Exception:
    _kDetectSpacingMs = 0

# ---------------------------------------------------------------------------
# Analysis cadence, and the one case worth breaking it for.
#
# The 500 ms floor used to be a bare local (kMinAnalyticsInterval) inside
# _requestDetections.  Against a 10 fps analysis stream (BackEndApp kFpsLimit)
# it means four of every five frames are never looked at, and a track whose
# whole life falls between two sampling instants is never handed to the
# detector AT ALL: it force-decides on an empty vote, which is the "no frames!"
# line.  Measured over the 3.35 h to 2026-09-02 19:21 (the window objdb2 holds
# after that day's reset): 1,655 such tracks fleet-wide, 17.5% of the 9,483
# stored as unclassified 'object'.  The other 82% ran the detector and still
# came back unknown; that is a separate problem and this does not address it.
#
# The FIRST sample is the only one worth an off-cadence frame, because it is
# the only one that changes an outcome categorically -- from no evidence to
# some.  A bypass frame therefore carries ONLY the never-sampled objects, and
# does not re-base the cadence: pulling the established population's budget
# forward would land all four _kFastDetectSamples within a few hundred ms of
# each other, which is exactly the front-loading the block above exists to
# avoid.
#
# Cost is bounded twice, because newborns arrive in bursts (a wind gust births
# many blobs at once) even though the mean rate is low:
#
#   * _kBypassBurst tokens, refilled one per _kBypassRefillMs.  The burst is
#     held BELOW ObjectDetectorClient._kMaxPendingWorkItems so a full burst can
#     never itself be the enqueue that evicts a pending item -- an eviction
#     publishes an empty result, which votes "unknown" for every object in the
#     evicted frame, so an over-eager bypass buys one first sample and pays a
#     whole frame of abstentions for it.
#   * the client's queue depth, read directly.  That is the actual question --
#     can the detector absorb one more right now -- and no clock answers it.
#
# A flat sub-floor would be useless here: frames arrive every ~100 ms at 10 fps,
# so any floor below that admits everything and bounds nothing.  The brakes have
# to be burst-shaped.
#
# Headroom, measured on DetectionService.log 2026-08-14..2026-09-02: the fleet
# averages 36 model calls/min, peaks at 297, and has never dropped a request on
# the service deadline.  What IS tight is burst latency on the single inference
# lock -- 1,375 requests over 1 s, p50 937 ms of that queued on the lock, max
# 21.6 s -- and that is what already produces the "(stale)" work-item drops in
# the camera logs.
# How long a detector-membership entry (_requestedObjects) is kept waiting for
# its result.  Sized off the DETECTOR's clock, not the decision clock: one work
# item is 1+4N RPCs at up to DetectionServiceClient._kRequestTimeout (30 s)
# each, so 10 s -- the force-decision timeout this originally borrowed -- is far
# too short and was observed dropping live entries under lock contention.  See
# the purge in _processDetections.
_kRequestedObjectsTtlMs = 60000

# How long terminate() will wait for the detector client, across both its
# stages.  Generous enough to let a normal in-flight work item finish -- the
# usual case is that _flushPipeline already ran reset() and there is nothing
# to wait for -- but bounded, because the alternative is parking camera
# shutdown on a wedged detector until the back end kills the process.
_kTerminateTimeoutSecs = 10.0

try:
    _icCfg = _icLoadConfig()
    _kMinAnalyticsIntervalMs = int(_icCfg.get("MIN_ANALYTICS_INTERVAL_MS", 500))
    _kFirstSampleBypass = bool(_icCfg.get("FIRST_SAMPLE_BYPASS", True))
    _kBypassBurst = int(_icCfg.get("BYPASS_BURST", 3))
    _kBypassRefillMs = int(_icCfg.get("BYPASS_REFILL_MS", 500))
    _kTrackLostGraceMs = int(_icCfg.get("TRACK_LOST_GRACE_MS", 2000))
    del _icCfg
except Exception:
    _kMinAnalyticsIntervalMs = 500
    _kFirstSampleBypass = True
    _kBypassBurst = 3
    _kBypassRefillMs = 500
    _kTrackLostGraceMs = 2000

# How long a track must be absent from the tracker's output before readyToReport
# calls it lost.  It used to be ONE frame, while VideoPipeline carries an unmatched
# track for _kMotionCooldown (3 s) -- so a blob that flickered out for a frame was
# force-decided on whatever it had, and whatever walked back into the same track
# afterwards was never looked at.  Measured 2026-09-23 on 060_Garage 16:03:35: track
# 7889 was born on a doorway speck, missed 1.9 s after 91 ms, force-decided
# 'unknown' on one sample, then carried a person YOLO scored 0.91-0.95 at Jaccard
# 0.82-0.95 for five seconds.  That camera's 30 s line read 1.5 samples/object with
# 6 of 10 tracks decided under 500 ms.
#
# Replaying that camera's live tracks through this vote: 0 ms -> 10 of 10 tracks
# 'unknown' (as stored live); 1500 ms -> 4 'person' but not 7889 (its gap was
# 1.9 s); 2000-3000 ms -> 7889 'person' too, with nothing further gained.
#
# The cost is latency: _processDetections stops at the first unready frame, so a
# coasting track holds its camera's reports back by up to this much.  Must stay
# below _kForceDecisionTimeout; keep it at or under the tracker cooldown.
_kTrackLostGraceMs = max(0, min(_kTrackLostGraceMs, _kForceDecisionTimeout - 1))

##############################################################################
class CloudStats(object):
    """ Per-camera detection-outcome counters, reported periodically.

    WHY THIS IS NOT WHAT IT USED TO BE
    The old version scored the detector against Sentry's opinion of an object's
    type: confirmations / denials / improvements / missed.  Sentry has no
    opinion.  svsentry.Sentry is a stub; the live tracker is VideoPipeline's
    motion path, and _beginObject / _addObjectFrame create every object with the
    literal "unknown".  So sentryObjType is the same constant on every object in
    the process and the four-way branch collapsed: the first arm caught every
    UNCLASSIFIED track and booked it a confirmation, the third caught every
    classified one and booked it an improvement, and _denials and _missed were
    unreachable -- hard zero in every log this ever wrote.  "Sentry match rate"
    was printing the unclassified rate under a name meaning its opposite.
    (The `is` on a string in the second arm was a real bug too, but fixing only
    that would have left the branch dead: the arm above already swallowed it.)

    It also logged at DEBUG while the deployed level is INFO, so it has never
    printed a line in production -- dead instrumentation for its whole life.
    Meanwhile the one member of the _summarizeScores family that DID print was
    the "no frames!" ERROR, which is why that error looked like the whole story
    instead of the ~17% of unclassified tracks it actually is.

    What needs measuring is the outcome MIX, so that the tracks the detector
    looked at and still failed to classify are visible as a number rather than
    as silence.  Everything here is derived from the object at report time, so
    no call site has to change and nothing is threaded through _summarizeScores.
    """

    # TRACK DURATION in ms -- how long Sentry saw the object, first sighting
    # to last.  NOT time-to-decision, which an earlier version of this comment
    # claimed: an object forced out by the `abandoned` backstop decides at
    # least _kForceDecisionTimeout after its last sighting, and one delayed by
    # head-of-line blocking decides later still, so the two quantities are not
    # interchangeable.
    #
    # Track duration is the right axis and must not be "corrected" to decision
    # time.  The question this histogram answers is "how does classification
    # rate vary with how long the object was visible", which is what the
    # hand-built histogram that motivated this work measured, and what every
    # recorded baseline is expressed in -- including the matched-hours 2.0x
    # result, whose reading ("short buckets improved because of the
    # first-sample bypass") is only meaningful for duration.  Changing the
    # measurement would silently break comparability with all of it.
    #
    # Boundaries match that histogram so the line can be compared straight
    # against it.
    _kDurationBucketsMs = (500, 1000, 2000, 3500, 6000, 10000)

    ###########################################################
    def __init__(self, reportInterval):
        super(CloudStats, self).__init__()
        self._reportInterval = reportInterval
        self._lastLogTime = time.time()
        self._lastDropped = 0
        self._lastBypassSkipped = 0
        self._totObjects = 0
        self._totClassified = 0
        self._resetInterval()

    ###########################################################
    def _resetInterval(self):
        self._objects = 0        # objects reported this interval
        self._classified = 0     # ... that got a real type
        self._unclassified = 0   # ... detector ran, still 'unknown'
        self._noFrames = 0       # ... detector never ran (frameCount == 0)
        self._samples = 0        # detection requests sent
        self._results = 0        # detection results counted against objects
        self._phantom = 0        # results counted against an unsampled object
        self._byType = {}
        self._durTotal = [0] * (len(self._kDurationBucketsMs) + 1)
        self._durClassified = [0] * (len(self._kDurationBucketsMs) + 1)

    ###########################################################
    def record(self, obj):
        """ Fold one reported object into the interval counters.

        @param  obj  The _QueuedObjId being reported for the first time.
        """
        self._objects += 1
        self._totObjects += 1
        self._samples += obj.detectionsRequested
        self._results += obj.detectionEventsCount

        # Results counted against an object that was NOT in the work item.
        # Should be zero: _processCloudResults notifies exactly the requested
        # set.  Kept because it is the cheapest possible watch on that
        # regression coming back, and because it is the single number that
        # shows the fix landed -- it was non-zero on every busy camera before.
        self._phantom += max(0, obj.detectionEventsCount - obj.detectionsRequested)

        decision = obj.detectorDecision
        if not obj.externalDetections:
            # frameCount == 0, the exact condition behind the "no frames!" log.
            self._noFrames += 1
        elif decision is None or decision == _kUnknownType:
            self._unclassified += 1
        else:
            self._classified += 1
            self._totClassified += 1
            self._byType[decision] = self._byType.get(decision, 0) + 1

        # Track duration, not time-to-decision -- see _kDurationBucketsMs.
        trackMs = max(0, obj.lastSeenBySentry - obj.firstSeenBySentry)
        idx = 0
        while idx < len(self._kDurationBucketsMs) and \
                trackMs >= self._kDurationBucketsMs[idx]:
            idx += 1
        self._durTotal[idx] += 1
        if decision is not None and decision != _kUnknownType:
            self._durClassified[idx] += 1

    ###########################################################
    def writeToLog(self, logger, droppedWorkItems=0, bypassSkipped=0):
        """ Emit one line per interval, then reset the interval counters.

        Deltas first, cumulative second, the same shape as
        DetectionService's heartbeat, because the rate is the interesting
        quantity and a running total cannot be differenced across the frequent
        camera-process restarts.  Silent when the interval saw nothing at all,
        also copying the heartbeat -- but "nothing" counts samples and drops,
        not just reports, so a camera that is sampling and never reporting (the
        readyToReport wedge) still prints, with objects=0 and samples>0.

        @param  logger            Camera logger.
        @param  droppedWorkItems  Cumulative count from the detector client.
        @param  bypassSkipped     Cumulative first-sample frames the token
                                  bucket or a full detector queue turned away.
                                  Rising alongside a high noFrames means the
                                  brakes are too tight for this camera, not
                                  that the bypass is failing.
        """
        now = time.time()
        elapsed = now - self._lastLogTime
        if elapsed < self._reportInterval:
            return

        dropped = max(0, droppedWorkItems - self._lastDropped)
        self._lastDropped = droppedWorkItems
        skipped = max(0, bypassSkipped - self._lastBypassSkipped)
        self._lastBypassSkipped = bypassSkipped
        self._lastLogTime = now
        if not (self._objects or self._samples or dropped):
            self._resetInterval()
            return

        types = ",".join("%s:%d" % kv for kv in sorted(self._byType.items())) \
                or "-"
        byDur = " ".join("%d/%d" % (c, t) for c, t
                         in zip(self._durClassified, self._durTotal))
        # Guarded: an interval with samples but no reports is exactly the wedge
        # signature, and dividing by objects there would take the camera
        # process down with the thing it was meant to diagnose.
        perObj = (self._samples / float(self._objects)) if self._objects else 0.0
        totPct = (100.0 * self._totClassified / float(self._totObjects)) \
                 if self._totObjects else 0.0

        logger.info(
            "detect %.0fs: objects=%d classified=%d unclassified=%d"
            " noFrames=%d samples=%d results=%d phantom=%d dropped=%d"
            " bypassSkipped=%d perObj=%.1f types=%s byDur=%s"
            " totObjects=%d totClassified=%.1f%%" %
            (elapsed, self._objects, self._classified, self._unclassified,
             self._noFrames, self._samples, self._results, self._phantom,
             dropped, skipped, perObj, types, byDur, self._totObjects, totPct))
        self._resetInterval()

##############################################################################
class QueuedDataManagerCloud(ObjectCollector):
    """An interface to DataManager functions to be processed remotely.

       Responsible for interpolating the results for frames not submitted to
       Sentry, as well as re-confirming classification of the objects by submitting
       frames with tracked objects to the cloud.
    """


    ###########################################################
    def __init__(self, msgQueue, pipe, id, cameraLocation, archiveDir, thumbRes, logger, inProcess=False):
        """Initialize QueuedDataManager.

        @param  msgQueue        A queue to add commands to.
        @param  pipe            A pipe for receiving feedback.
        @param  id              An id to accompany all commands.
        @param  cameraLocation  The camera location for the object.
        @param  logger          A logging utils instance.
        """
        # Call the superclass constructor.
        super(QueuedDataManagerCloud, self).__init__()

        # This is publicly accessible in case the camera location changes.
        self.cameraLocation = cameraLocation

        self._logger = logger
        self._queue = msgQueue
        self._pipe = pipe
        self._id = id

        self._objectsAdded = 0
        self._prevObjectsAdded = 0
        # deque, not list: _checkForRealDbIds drains this from the head on
        # every addFrame(), and list.pop(0) shifts the whole tail each time.
        # Harmless while the back end keeps up; O(n^2) to drain if it ever
        # falls behind and the list backs up.
        self._temporaryIdList = deque()
        self._initInterpolationState()
        # Frames currently being processed by the Sentry or by the cloud
        self._frames = {}
        self._lastFrameSavedTime = 0
        self._archiveDir = archiveDir
        self._thumbRes = thumbRes
        self._lastAnalyzedFrameMs = None
        # Token bucket bounding off-cadence first-sample frames; see the
        # _kBypassBurst comment block.
        self._bypassTokens = float(_kBypassBurst)
        self._lastBypassMs = None
        self._bypassSkipped = 0
        # Last frame to flush out of here and into the backEnd
        self._lastFrameCompletedMs = 0

        # Objects reported to us by Sentry, but not yet submitted to backEnd
        self._trackedObjects = {}
        # Number of objects processed in the last frame
        self._objectsInLastFrame = 0

        # timestamp -> the _QueuedObjId objects actually handed to the detector
        # for that frame.  _processCloudResults used to notify every object in
        # _trackedObjects[timestamp] instead, which is wrong the moment the
        # request list is a SUBSET of the frame.  needsDetection makes it one
        # whenever an undecided object is held back -- which _kDetectSpacingMs
        # does by design -- and notifyDetectionCompleted early-returns only for
        # objects that have already DECIDED, so a held-back object collected an
        # ("unknown", 0.5, 0.5) vote for a frame it was never sampled in.
        #
        # The damage runs through the count, not the vote: needsDetection gates
        # sampling on detectionsRequested, but readyToReport force-decides on
        # detectionEventsCount, and only the latter is inflated.  So on a busy
        # camera an object was decided at "8 events" having genuinely been
        # sampled 2-4 times, on a vote made mostly of abstentions it never
        # earned -- while still entitled to real samples it now never gets.
        # That is why DETECT_SPACING_MS had to be reverted to 0 the day it
        # shipped; it cannot be re-enabled until this is in place.
        self._requestedObjects = {}

        self._outstandingDetectionRequests = 0

        self._lastSentryFrameTimeMs = 0

        if inProcess:
            self._httpClient = ObjectDetectorClientInProcess(self.cameraLocation, self._logger)
        else:
            self._httpClient = ObjectDetectorClientImageCheck(self.cameraLocation, self._logger)
        self._httpClient.start()

        self._stats = CloudStats(_kStatsReportInterval)

        self._debugMode = not hasattr(sys, 'frozen')



    ###########################################################
    def __del__(self):
        """Destructor for QueuedDataManager."""
        self.terminate()

        try:
            # Inform the back end that our pipe is no longer in use.
            self._queue.put([MessageIds.msgIdPipeFinished, self._id])
        finally:
            # Our base class, ObjectCollector, implements `__del__` also. Make
            # sure we call it without fail...
            super(QueuedDataManagerCloud, self).__del__()

    ###########################################################
    def terminate(self, timeout=_kTerminateTimeoutSecs):
        """Shut the detector client down, without waiting on it forever.

        Both waits are bounded now.  ObjectDetectorClient.terminate() can
        discard work items that are still QUEUED, but it cannot interrupt one
        already inside _processWorkItem -- and that is 1+4N RPCs at up to
        DetectionServiceClient._kRequestTimeout (30 s) each, behind an
        inference lock measured queueing as long as 21.6 s.  A plain join()
        therefore parks the camera process on shutdown for as long as the
        detector takes, or forever if it is wedged, until the back end's
        watchdog kills the process out from under it.

        flush() directly below uses this same timeout-then-continue shape, as
        does the WSGI shutdown in CameraCapture._cleanup; this is the local
        idiom, not a new one.

        @param  timeout  Total seconds to spend waiting, across both stages.
        """
        if self._httpClient is not None:
            self._logger.debug("Destroying HTTP client")
            if self._httpClient.is_alive():
                start = time.time()
                while self._outstandingDetectionRequests > 0:
                    self._logger.debug("Destroying HTTP client - waiting for " + str(self._outstandingDetectionRequests) + " pending results")
                    self._processDetections()
                    if time.time() - start > timeout:
                        self._logger.warning(
                            "Destroying HTTP client - %d result(s) never "
                            "arrived after %.1fs; giving up on them" %
                            (self._outstandingDetectionRequests, timeout))
                        break
                    if self._outstandingDetectionRequests > 0:
                        time.sleep(0.1)

                self._logger.debug("Destroying HTTP client - terminating")
                self._httpClient.terminate()
                self._logger.debug("Destroying HTTP client - waiting ...")
                self._httpClient.join(max(0.0, timeout - (time.time() - start)))
                if self._httpClient.is_alive():
                    self._logger.warning(
                        "Destroying HTTP client - worker still running after "
                        "%.1fs; abandoning it (it is a daemon thread and the "
                        "process is going away)" % timeout)
                else:
                    self._logger.debug("Destroying HTTP client - done")
            self._httpClient = None

    ###########################################################
    def setDebugFolder(self, folder):
        self._httpClient.setDebugFolder(folder)

    ###########################################################
    def _initInterpolationState(self):
        # Total number of frames interpolated from the start and until the currently
        # processed frame was first seen from Sentry
        self._totalInterpolated = 0
        # Current frame we receive objects for
        self._currentFrameTime = None
        self._currentFrameId = None
        # Previous frame we received objects for
        self._previousFrameTime = None
        # All the objects reported for the current frame
        self._currentFrameObjs = {}
        # All the objects reported for previous frame
        self._previousFrameObjs = {}
        # Frames lost to analytics that we need to interpolate for
        self._lostFrames = deque([])
        # Frames interpolated for current timestamp
        self._interpolatedFrames = 0
        # Timestamp of previous frame we ran interpolation for
        self._prevInterpolationTime = 0
        # Frames for submission to DB processed for the current time
        self._savedFrames = []

    ###########################################################
    def setThumbnailResolution(self, res):
        self._thumbRes = res

    ###########################################################
    def reset(self):
        """ Reset our state entirely, before new video stream starts fresh

        Called from CameraCapture._flushPipeline when the stream is re-opened,
        which is the one moment we are entitled to drop in-flight work.  It
        used to reset interpolation only, so a pipeline that had wedged on an
        undecided object (see readyToReport) carried the wedge straight across
        the reconnect -- 05_Gate_lr survived two stream recoveries on
        2026-08-29 still mute.  Nothing here is recoverable across a restart:
        the frames are gone and any detector reply still in flight refers to
        timestamps this pipeline will never report.
        """
        self._initInterpolationState()
        self._trackedObjects = {}
        self._frames = {}
        self._outstandingDetectionRequests = 0
        self._objectsInLastFrame = 0
        # Refill the bypass bucket and forget the last bypass time: after a
        # reconnect the next frame's timestamp bears no useful relation to the
        # old one, and a stale _lastBypassMs would refill the bucket by however
        # long the stream was down.
        self._bypassTokens = float(_kBypassBurst)
        self._lastBypassMs = None
        # Deliberately NOT clearing _requestedObjects -- see the purge in
        # _processDetections for why an in-flight result must keep its list.

    ###########################################################
    def _checkTime(self, time, frameId):
        """ Checks the object state against new frame coming in,
            and modifies the state if new frame is detected
        """
        if self._currentFrameTime is None:
            # This is the first time we receive anything
            self._currentFrameTime = time
            self._currentFrameId = frameId
            return

        # Current implementation of Sentry serializes frames, until
        # all the objects had been labeled.
        # This may change in the future: when/if it will, most of the code here
        # and interpolation in particular will have to change
        assert time >= self._currentFrameTime

        if self._currentFrameTime == time:
            # Time hasn't changed yet
            assert frameId == self._currentFrameId
            return

        # Time had changed
        self._previousFrameTime = self._currentFrameTime
        self._previousFrameObjs = self._currentFrameObjs
        self._currentFrameTime = time
        self._currentFrameId = frameId
        self._currentFrameObjs = {}

        counter = 0
        while len(self._lostFrames) > 0 and \
            self._lostFrames[0] <= self._previousFrameTime:
            self._lostFrames.popleft()
            counter += 1
        self._totalInterpolated += counter

    ###########################################################
    def reportFrame(self, ms, frameObj=None):
        """Notify QueuedDataManager about a frame submitted to pipeline
        """
        if frameObj is None:
            # This is a dummy frame reported for interpolation purposes only
            # Pipeline hasn't seen it
            if self._currentFrameTime is None or \
               ms > self._currentFrameTime:
                self._lostFrames.append(ms)
            else:
                self._logger.error("Attempting to report frame from " + str(ms) +
                        " for interpolation. Currently processing " +
                        str(self._currentFrameTime) )
        else:
            # This is an actual frame, that is reported to the pipeline
            self._frames[ms] = frameObj

    ###########################################################
    def addObject(self, timeStart, objType=_kUnknownType):
        """Overloaded method. Insert an object into the database

        @param  timeStart       The time the object first came into view
        @param  objType         The type of this object, like 'person' or
                                'object'.
        @return objId           The id for this object assigned by the database
        """
        camObjId = self._objectsAdded
        self._objectsAdded += 1
        self._logger.debug( "addObject: " + str(timeStart) + " type=" + objType + " id=" + str(camObjId))

        queuedObjId = _QueuedObjId(self._id, camObjId, timeStart, objType)
        self._temporaryIdList.append(queuedObjId)

        # Always save a thumbnail of the first frame of each object
        if self._lastFrameSavedTime < timeStart:
            self._saveFrameThumbnail(timeStart)

        return queuedObjId.sentryId

    ###########################################################
    def _flushSavedObjects(self):
        self._interpolatedFrames = 0
        # Flush frames with previous timestamp
        for savedFrame in self._savedFrames:
            self._addFrameToDb(*savedFrame)
        self._savedFrames = []

    ###########################################################
    def setAnalyticsPort(self, port):
        if self._httpClient is not None:
            self._httpClient.setAnalyticsPort(port)

    ###########################################################
    def _applyRatio(self, listOfObjects, sizeRatio):
        res = []
        for obj in listOfObjects:
            newBox = tuple([int(z * sizeRatio) for z in obj[2]])
            res.append( (obj[0], obj[1], newBox) )
        return res

    ###########################################################
    def _bypassAllowed(self, ms):
        """May we spend an off-cadence work item on a newborn track right now?

        @param  ms  Timestamp of the candidate frame.
        @return ok  True if a token was spent and the caller may enqueue.
        """
        if not _kFirstSampleBypass:
            return False

        # Never enqueue into a nearly-full client queue.  enqueWorkItem does
        # not block; on overflow it DISCARDS THE OLDEST pending item, and a
        # discarded item still publishes an empty result -- one abstention vote
        # for every object in the discarded frame.  Leaving a slot free means
        # the bypass can never be the enqueue that forces that trade.
        if self._httpClient.pendingWorkItems() >= _kClientQueueBound - 1:
            self._bypassSkipped += 1
            return False

        if self._lastBypassMs is not None:
            self._bypassTokens = min(
                float(_kBypassBurst),
                self._bypassTokens +
                (ms - self._lastBypassMs) / float(_kBypassRefillMs))
        self._lastBypassMs = ms
        if self._bypassTokens < 1.0:
            self._bypassSkipped += 1
            return False
        self._bypassTokens -= 1.0
        return True

    ###########################################################
    def _requestDetections(self, timestamp):
        """ Run cloud detection on the frame, if a full-size frame exists for this timestamp
        """
        frame = self._frames.get(timestamp, None)
        if frame is None:
            return

        # Answer "does anything here still want the detector?" BEFORE applying
        # the cadence floor.  It used to be answered after, which is why a
        # track shorter than the sampling interval could never be looked at:
        # the floor turned the frame away before anyone asked who was in it.
        #
        # .get, not [], because with the floor no longer in front of it this
        # runs on every motion frame rather than twice a second, and
        # _addFrameToDb tolerates a timestamp whose objects have been purged.
        #
        # Objects we've already decided about are excluded here (person objects
        # stay eligible post-report at a throttled rate for late face/nudity
        # attribute updates -- see needsDetection).
        pending = [s for s in self._trackedObjects.get(timestamp, ())
                   if s[0].needsDetection(timestamp)]
        if not pending:
            # Return WITHOUT touching _lastAnalyzedFrameMs.  That assignment
            # used to sit above this test, so a frame that enqueued nothing
            # still consumed the interval: the cadence free-ran against wall
            # time and a track born just after a barren tick could wait most of
            # a second for a look it was entitled to immediately.
            return

        if frame.wasResized:
            # Try to obtain a full-size frame.  Dead today -- StreamReader._Frame
            # defaults wasResized False, nothing in the tree constructs it True,
            # and getLargeFrame() unconditionally returns None -- kept because
            # it is the hook a real multi-resolution reader would use.
            frameForAnalyzing = frame.getLargeFrame()
            if frameForAnalyzing is None:
                return
            listToSend = pending
            self._lastAnalyzedFrameMs = frameForAnalyzing.ms
        else:
            frameForAnalyzing = frame
            onCadence = (self._lastAnalyzedFrameMs is None or
                         frame.ms - self._lastAnalyzedFrameMs >=
                         _kMinAnalyticsIntervalMs)
            if onCadence:
                listToSend = pending
                # Only a cadence frame re-bases the cadence.  A bypass is purely
                # additive; re-basing on one would drag every other object's
                # schedule along with it.
                self._lastAnalyzedFrameMs = frameForAnalyzing.ms
            else:
                newborn = [s for s in pending if s[0].detectionsRequested == 0]
                if not newborn or not self._bypassAllowed(frame.ms):
                    return
                listToSend = newborn

        sizeRatio = frame.width / float(frameForAnalyzing.width)

        if self._debugMode:
            self._logger.debug("[detect] enqueueing ts=%d objects=%d%s"
                    % (timestamp, len(listToSend),
                       "" if listToSend is pending else " (first-sample)"))
        for idObj, _, _ in listToSend:
            idObj.notifyDetectionRequested(timestamp)

        # Record exactly who is in this work item.  _processCloudResults reads
        # this to decide who the result notifies; without it the objects NOT in
        # the item collect phantom abstentions (see _requestedObjects).
        self._requestedObjects[timestamp] = [s[0] for s in listToSend]

        if self._debugMode:
            self._logger.debug("Detection request: %d - %s" % (timestamp, str(self._applyRatio(listToSend, sizeRatio))))
        self._httpClient.enqueWorkItem(timestamp, frameForAnalyzing, listToSend, sizeRatio)

        self._outstandingDetectionRequests += 1

    ###########################################################
    def _frameReadyToReport(self, ms, sentryLastProcMs):
        """ Frame is ready for reporting, when all objects
            in this frame are ready
        """
        frames = self._trackedObjects.get(ms, None)
        if frames is None:
            return True

        # Iterate on objects tracked in this frame, and check if we have
        # the final verdict from the cloud, or if we've lost the object
        # before the said verdict could arrive
        for track in frames:
            obj = track[0]
            if not obj.readyToReport(sentryLastProcMs, self._logger):
                return False

        return True

    ###########################################################
    def _buildAttrsDict(self, obj, objType):
        """Assemble the detection-attributes dict for an object report/update.

        Sent as a dict so new fields can be added without changing the message
        contract.  Returns None for types that carry no attributes.

        @param  obj      The _QueuedObjId.
        @param  objType  The object's decided type.
        @return attrs    Dict of attributes, or None.
        """
        if objType not in ('person', 'vehicle', 'animal'):
            return None

        attrs = {
            'subType': obj.subType,
            'detConf': obj.detConf if obj.detConf else None,
        }
        if objType == 'person':
            attrs.update({
                'faceName':     obj.bestFaceName,
                'faceConf':     (obj.bestFaceScore
                                 if obj.bestFaceName else None),
                'faceDetConf':  obj.faceDetConf,
                'gender':       obj.gender,
                'age':          obj.age,
                'nudity':       obj.sawNudity,
                'nudityDetail': obj.nudityDetail,
            })
        return attrs


    ###########################################################
    def _generateFrameReport(self, ms):
        """ Send messages to backEnd for all objects in this frame
        """
        frames = self._trackedObjects.get(ms, None)
        if frames is None:
            return

        for obj, frameId, bbox in frames:
            objType = obj.getType()

            if not obj.reported:
                camObjId = obj.dbId[1]
                attrs = self._buildAttrsDict(obj, objType)
                self._queue.put([MessageIds.msgIdDataAddObject, self._id,
                          camObjId, ms, objType, self.cameraLocation, attrs])
                self._stats.record(obj)
                obj.reported = True
                obj.attrsDirty = False
            elif obj.attrsDirty:
                # Attributes materially improved after the object was reported
                # (e.g. face recognized as the person got closer) — send the
                # complete, current attrs so the DB row is replaced.
                attrs = self._buildAttrsDict(obj, objType)
                if attrs:
                    self._queue.put([MessageIds.msgIdDataUpdateObjectAttrs,
                                     self._id, obj.dbId, attrs])
                obj.attrsDirty = False

            self._queue.put([MessageIds.msgIdDataAddFrame, self._id,
                            obj.dbId,
                            frameId, ms, bbox, objType, None])

        # update the stats
        self._stats.writeToLog(self._logger,
                               self._httpClient.droppedWorkItems()
                               if self._httpClient is not None else 0,
                               self._bypassSkipped)

        # Remember the last ms processed
        self._lastFrameCompletedMs = ms

    ###########################################################
    def getFinishedTimestamp(self):
        """ Return the last timestamp we're absolutetly done with
        """
        return self._lastFrameCompletedMs

    ###########################################################
    def _processCloudResults(self):
        while True:
            result = self._httpClient.getNextResult()
            if result is None:
                break

            # Floor at zero.  reset() drops in-flight requests when the stream
            # is re-opened, but the detector thread may still publish results
            # for them afterwards; letting the count go negative would make
            # the "no work outstanding" test below (== 0) unsatisfiable and
            # freeze _lastFrameCompletedMs for good -- the exact wedge this
            # file is being fixed for.
            self._outstandingDetectionRequests = \
                max(0, self._outstandingDetectionRequests - 1)

            # First let objects where the positive detection occurred know
            timestamp, detections = result
            if self._debugMode:
                self._logger.debug("[detect] result ts=%d detections=%d" % (timestamp, len(detections)))
            if self._debugMode:
                self._logger.debug("Detection response: %d - %s" % (timestamp, str(detections)))
            for obj, type, score, overlap in detections:
                obj.reportCloudDetection(timestamp, type, score, overlap, self._logger)

            # And then let the rest of THIS WORK ITEM know the detection had
            # occurred.  Deliberately not every object in _trackedObjects for
            # this frame: an object the request list excluded was not looked
            # at, so telling it a detection completed hands it an abstention
            # vote and a detectionEventsCount increment it never earned.  See
            # _requestedObjects in __init__ for what that costs.
            notified = set()
            frames = self._requestedObjects.pop(timestamp, None)
            if frames is not None:
                for obj in frames:
                    obj.notifyDetectionCompleted(timestamp)
                    notified.add(obj.sentryId)
            elif timestamp <= self._lastFrameCompletedMs:
                # Expected, not an error: the detector answers asynchronously,
                # and reset() can orphan a membership entry that the purge in
                # _processDetections then ages out before its result lands.
                # The detections themselves were already applied above, before
                # this lookup, and the loop below still notifies every object
                # the result carried.  Logged for the lag, which is the number
                # worth watching: a steady sub-second gap is normal, one that
                # keeps growing means the detector is falling behind capture.
                self._logger.debug("Detection result for %d arrived %dms after "
                        "the frame was reported" %
                        (timestamp, self._lastSentryFrameTimeMs - timestamp))
            else:
                # Reports on the membership map, which is what was actually
                # consulted -- _trackedObjects would describe a different
                # question and send the next reader down the wrong path.
                timestamps = sorted(self._requestedObjects.keys())
                tLen = len(timestamps)
                if tLen > 0:
                    self._logger.error("Couldn't find timestamp " + str(timestamp) + \
                        " have [" + str(timestamps[0]) + "," + str(timestamps[tLen-1]) + "]")
                else:
                    self._logger.error("Couldn't find timestamp " + str(timestamp) + ": no requests outstanding")

            # Objects carried in the result are notified even when their frame
            # is no longer tracked.  Both branches above notify nobody, which
            # leaves an object that outlived its frame with
            # lastDetectionResponseTime stuck behind lastDetectionRequestTime
            # -- readyToReport then reads it as "still waiting on the
            # detector" forever, and one such object wedges the camera (see
            # readyToReport).  The set guards notifyDetectionCompleted's
            # detectionEventsCount, which is NOT idempotent per call.
            for obj, _, _, _ in detections:
                if obj.sentryId not in notified:
                    obj.notifyDetectionCompleted(timestamp)
                    notified.add(obj.sentryId)



            # self._logger.debug("Got result from the cloud for %d" % result[0])

    ###########################################################
    def _processDetections(self):
        self._processCloudResults()

        # See if there's anything to report to backEnd
        for k in sorted(self._trackedObjects.keys()):
            if not self._frameReadyToReport(k, self._lastSentryFrameTimeMs):
                break

            self._generateFrameReport(k)
            del self._trackedObjects[k]

        # Free all the frames that aren't needed anymore
        for timestamp in list(self._frames.keys()):
            if timestamp <= self._lastSentryFrameTimeMs:
                del self._frames[timestamp]

        # Age out orphaned detector-membership entries.  Entries are normally
        # consumed by the result they belong to, so this only ever collects
        # what reset() stranded.  Deliberately NOT cleared in reset(): an
        # in-flight result would lose its notification list, and its objects
        # would stop advancing lastDetectionResponseTime -- the wedge
        # readyToReport documents.
        #
        # The retention MUST outlast the slowest legitimate round trip, which is
        # a detector clock, not a decision clock.  This was originally
        # _kForceDecisionTimeout (10 s) -- wrong, and measured wrong: on
        # 2026-09-03 at 13:52, with the service at 20 threads and ~3 s of lock
        # queueing, a result came back after its entry had been purged and hit
        # the "Couldn't find timestamp" branch.  A work item can legitimately
        # take far longer than 10 s: DetectionServiceClient._kRequestTimeout is
        # 30 s PER RPC and _processWorkItem issues 1+4N of them for N persons.
        # (Queue wait is bounded separately -- _kMaxWorkItemAgeMs drops items
        # that waited over 5 s -- so this only has to cover processing.)
        #
        # Purging early is not fatal, because objects carried in the result are
        # still notified by the loop in _processCloudResults and the abandoned
        # backstop eventually frees the rest, but work-item objects that matched
        # nothing lose their abstention and sit until that backstop fires.  The
        # cost of being generous is one dict entry per enqueue per minute, so be
        # generous.
        for timestamp in list(self._requestedObjects.keys()):
            if timestamp < self._lastSentryFrameTimeMs - _kRequestedObjectsTtlMs:
                del self._requestedObjects[timestamp]

        # Purge old objects
        _QueuedObjId.purgeOldIds(self._lastSentryFrameTimeMs)

    ###########################################################
    def flush(self, timeout):
        self._logger.debug("Flushing the data queue")
        start = time.time()
        while self._outstandingDetectionRequests > 0:
            # try processign new cloud detections
            self._processDetections()
            # put a limit to how long we wait for the results to flush
            if time.time() - start > timeout:
                break
            # wait a bit before polling again
            if self._outstandingDetectionRequests > 0:
                time.sleep(0.1)
        self._logger.debug("Still tracking objects in " + str(len(self._trackedObjects)) + " frames")

    ###########################################################
    def frameCompleted(self, msTimestamp, frameNum):
        """ Callback from Sentry, invoked when processing for frame with msTimestamp
            is completed, and no more events for it should be expected
        """
        # Save all the tracks from the last frame
        self._flushSavedObjects()

        # Run cloud detections, if there's anything to recognize
        if self._objectsInLastFrame > 0:
            self._requestDetections(msTimestamp)
            self._objectsInLastFrame = 0

        self._lastSentryFrameTimeMs = msTimestamp
        self._processDetections()

        # Also emitted here, not only from _generateFrameReport.  That was the
        # single call site, and it never runs on a camera whose reporting has
        # wedged (see readyToReport) -- exactly the camera you most want a line
        # out of.  Cheap: the interval test is the first thing writeToLog does.
        if self._httpClient is not None:
            self._stats.writeToLog(self._logger,
                                   self._httpClient.droppedWorkItems(),
                                   self._bypassSkipped)

        # if there is no outstanding detections requests,
        # and no objects are currently being tracked, we're done up to this frame
        if self._outstandingDetectionRequests == 0 and \
            len(self._trackedObjects) == 0:
            self._lastFrameCompletedMs = msTimestamp

    ###########################################################
    def _saveFrameThumbnail(self, ms):
        if self._thumbRes == 0:
            return
        frame = self._frames.get(ms, None)
        if frame is None:
            self._logger.error("Requested timestamp " + str(ms) + " is not available for thumb")
            return
        pilFrame = convertProcFrameToPIL(frame)
        dirname = os.path.join(self._archiveDir, self.cameraLocation.lower(), _msToFolder(ms), kThumbsSubfolder)

        saveTo = os.path.join(dirname, str(ms)+".jpg")
        self._logger.debug("Saving jpg to " + saveTo)
        # Resize the frame, if requested thumb size is less than what we have
        if self._thumbRes < pilFrame.width:
            # This ensures the image gets scaled down to the requested size on smaller dimension
            kVeryLargeFactor = 20
            if pilFrame.width > pilFrame.height:
                size = (self._thumbRes*kVeryLargeFactor, self._thumbRes)
            else:
                size = (self._thumbRes, self._thumbRes*kVeryLargeFactor)
            pilFrame.thumbnail(size, Image.Resampling.LANCZOS)
        try:
            if not os.path.isdir(dirname):
                os.makedirs(dirname)
            pilFrame.save(saveTo, "JPEG")
        except:
            self._logger.warning("Failed to save thumbnail to " + saveTo)

        # Even if we've failed to create a thumb, there's no reason to retry immediately
        self._lastFrameSavedTime = ms

    ###########################################################
    def _interpolateObjectAtTime(self, objId, t, frameId):
        """ Interpolate object's position at a specific time, using its positions
            in the previous and the current frames reported by Sentry
        """
        t1 = self._previousFrameTime
        b1, type1 = self._previousFrameObjs[objId]
        t2 = self._currentFrameTime
        b2, type2 = self._currentFrameObjs[objId]

        distance = t2 - t1
        d1 = t - t1
        d2 = t2 - t

        w1 = d1 / float (distance)
        w2 = d2 / float (distance)

        newBox = []
        for i in range(len(b1)):
            newBox.append( int(b1[i]*w2 + b2[i]*w1) )

        # Send a notification to the db
        self._addFrameToDb(objId, frameId, t, newBox, type1)

    ###########################################################
    def _realFrameId(self, offset):
        """ Calculate current frame ID, considering frames added by interpolation

        @param offset               How many frames had been added by interpolation
                                    while processing the current "Sentry" frame
        @return realFrameId         Converted frame ID
        """
        return self._currentFrameId + self._totalInterpolated + offset

    ###########################################################
    def _interpolateObject(self, objId):
        """ Run through the set of timestamps reported, but not submitted to Sentry,
            and interpolate the object position using its location in the last and current
            frames.
        """
        if self._previousFrameObjs is None or \
           self._currentFrameObjs is None:
            return 0
        if not objId in self._previousFrameObjs:
            return 0

        frameIdOffset = 0
        for t in self._lostFrames:
            # Only interpolate for frames in the past
            if t < self._currentFrameTime:
                self._interpolateObjectAtTime(objId, t, self._realFrameId(frameIdOffset))
                frameIdOffset += 1
            else:
                break
        return frameIdOffset

    ###########################################################
    def _addFrameToDb(self, objId, frameId, time, bbox, objType):
        # NOTE: That last message parameter that we send (`None` in this case)
        #       in the message queue is the `action` argument.
        #
        #       `action`: The action to add to the database; or None if none.
        #
        #       Previously, our pipeline runner was sending `None` anyway, but
        #       `addFrame()` used to have `action` as a parameter before we
        #       started using Sentry. So we just mention this here as a note
        #       for documentation pursposes.
        try:
            idObj = _QueuedObjId.getQueuedObjId(objId)
        except RuntimeError:
            return  # ID was already purged; skip this stale frame
        idObj.reportSeen(time, self._logger)
        # save the object for this ms
        self._trackedObjects.setdefault(time,[]).append((idObj, frameId, bbox))

    ###########################################################
    def addFrame(self, objId, frameId, time, bbox, objType):
        """Overloaded method. Add a new frame of data.
           Note: multiple calls may occur for the same frameId, is this method is called
                 for each object in the frame.

        @param  objId    The id of the object in the database
        @param  frameId  The number of the frame to add
        @param  time     The time in ms that matches frame
        @param  bbox     A bounding box for the object at the given frame
        @param  objType  The object's type; passed here for speed--
                         this should match the type used for addObject().
        """
        self._checkForRealDbIds()
        # Check if this is a new frame coming from Sentry
        self._checkTime(time, frameId)

        # Sentry uses OpenCV rectangle convention, where 2nd point is exclusive
        # We expect both points being inclusive. Validate data before correction.

        updatedX = bbox[2] - 1 if bbox[2] > bbox[0] else bbox[2]
        updatedY = bbox[3] - 1 if bbox[3] > bbox[1] else bbox[3]
        updatedBBox = (bbox[0], bbox[1], updatedX, updatedY)

        # Save into list of objects for current timestamp
        self._currentFrameObjs[objId] = (updatedBBox, objType)

        # If the time changes, we reset the interpolated frames count
        if time != self._prevInterpolationTime:
            self._flushSavedObjects()
        self._prevInterpolationTime = time

        # Attempt to interpolate with the previous frame
        interpolatedFrames = self._interpolateObject(objId)

        # The number of interpolated frames may differ from object to object
        # (since an object may be new to this frame) ... we need to keep frame IDs consistent
        if interpolatedFrames > self._interpolatedFrames:
            assert self._interpolatedFrames == 0
            self._interpolatedFrames = interpolatedFrames
            newSavedFrames = []
            # Update frame IDs for previous frames processed for this timestamp
            for f in self._savedFrames:
                newSavedFrames.append ((f[0], f[1]+interpolatedFrames, f[2], f[3], f[4]))
            self._savedFrames = newSavedFrames
        elif interpolatedFrames < self._interpolatedFrames:
            assert interpolatedFrames == 0

        # Send a notification to the db
        realFrameId = self._realFrameId(self._interpolatedFrames)

        if self._debugMode:
            self._logger.debug("Motion detected at %d - frameId=%d, rect=%s" % (time, realFrameId, str(updatedBBox)))

        self._savedFrames.append((objId, realFrameId, time, updatedBBox, objType))

        # Save a jpeg, if needed
        if self._lastFrameSavedTime + _kFrameSaveInterval < time:
            self._saveFrameThumbnail(time)

        self._objectsInLastFrame += 1


    ###########################################################
    @property
    def numTotalObjectsAdded(self):
        return self._objectsAdded

    ###########################################################
    @property
    def numObjectsAddedSinceLastCheck(self):
        objectsAddedSinceLast = self._objectsAdded - self._prevObjectsAdded
        self._prevObjectsAdded = self._objectsAdded
        return objectsAddedSinceLast


    ###########################################################
    def _checkForRealDbIds(self):
        """This polls our pipe looking for real database IDs."""

        # Data on the pipe should come back in the order we added objects.
        # If we get something unexpected, we'll just drop stuff from our
        # self._temporaryIdList until we match up, since it implies that the
        # back end somehow got mixed up.
        while self._pipe.poll(0):
            (tempId, realId) = self._pipe.recv()

            while self._temporaryIdList:
                queuedObjId = self._temporaryIdList.popleft()
                if queuedObjId.dbId == (self._id, tempId):
                    break
                else:
                    self._logger.warning("Never got mapping for ID %s" %
                                      str(queuedObjId.dbId))
            else: # didn't break; ran out of temporary IDs
                # Really don't expect this (how would an extra thing get in
                # the list?)  If we expected it, we should do something like
                # keep track of mappings that we tossed above, then restore
                # them all here.
                self._logger.error("Received unexpected mapping: %d -> %d" % (
                                   tempId, realId))
                return

            self._logger.debug("Received mapping: %d -> %d" % (
                               tempId, realId))

            queuedObjId.dbId = realId


##############################################################################
class _QueuedObjId(object):
    """Internal class that we return as the database ID.

    The reason that we have this class is that it easily allows us to switch
    from using our temporary ID to our real ID once the real ID arrives on
    the pipe.

    When we're running with a temprary ID, self.dbId will be a tuple:
      (camId, camObjId)
    ...once we get a real ID, it will just be the dbId returned by the data mgr.
    """

    _idToQueuedObj = {}
    _idNum = -1
    _idLastPurgeTime = int(time.time() * 1000)  # ms epoch
    _idPurgeInterval = 30 * 1000       # purge old IDs every 30s (in ms)
    _idPurgeTimeout = 5 * 60 * 1000   # ID is old after 5 min with no motion (in ms)
    _minDetectionEvents = 3
    _maxDetectionEvents = 8

    ###########################################################
    def __str__(self):
        return str(self._idNum) if self._idNum >= 0 else str(self._idToQueuedObj)
    __repr__ = __str__

    ###########################################################
    @classmethod
    def purgeOldIds(cls, ms):
        """ Remove objects not tracked any longer
        @param  ms      ms of the current frame being processed
        """
        if cls._idLastPurgeTime + cls._idPurgeInterval > ms:
            return
        # delete info about objects we haven't seen in awhile
        for idNum in list(cls._idToQueuedObj.keys()):
            if cls._idToQueuedObj[idNum].lastSeenBySentry + cls._idPurgeTimeout < ms:
                del cls._idToQueuedObj[idNum]
        cls._idLastPurgeTime = ms


    ###########################################################
    @classmethod
    def getQueuedObjId(cls, theId):
        qObjId = cls._idToQueuedObj.get(theId, None)
        if qObjId is not None:
            return qObjId
        raise RuntimeError("Id '%s' does not exist." % theId)


    ###########################################################
    def __init__(self, camId, camObjId, ms, objType):
        """_QueuedObjId constructor.

        @param  camId     The ID number of the queue.
        @param  camObjId  The number of objects that have been created
                          by the queue so far.
        """
        super(_QueuedObjId, self).__init__()

        _QueuedObjId._idNum += 1
        idNum = _QueuedObjId._idNum

        self.dbId = (camId, camObjId)
        self.sentryId = idNum
        self.firstSeenBySentry = ms   # first time this object had been seen by Sentry
        self.lastSeenBySentry = ms    # last time this object had been seen by Sentry
        self.sentryObjType = objType  # object type as Sentry sees it
        self.externalDetections = defaultdict(list) # detection results for all the past frames
        self.lastDetectionRequestTime = None        # last detection requested for a frame containing this object
        self.lastDetectionResponseTime = 0       # last time we've been notified of a detection response (not the same as result)
        self.lastDetectionEventTime = None          # timestamp of last supplied detection result
        self.detectionEventsCount = 0 # how many frames containing this object were analyzed by the detector
        self.detectorDecision = None  # The type we decide on, based on all factors
        self.detectionsRequested = 0   # number of detection requests sent for this object
        self.reported = False          # whether the object was reported
        self.sentryFramesSeen = 0     # number of times this object was seen by sentry

        # Detection attributes layered on top of the categorical type.  These
        # are tracked separately from the type vote so that face recognition
        # and nudity don't fragment / lose the person/vehicle/animal decision.
        self.bestFaceName = None      # best-scoring recognized face name so far
        self.bestFaceScore = 0.0      # recognition confidence of bestFaceName
        self.gender = None            # 'M'/'F' from the best face frame
        self.age = None               # estimated age from the best face frame
        self.faceDetConf = None       # face detection score from the best face
        self.subType = None           # specific YOLO class (dog/car/...) best by dc
        self.detConf = 0.0            # max YOLO detection confidence seen
        self.sawNudity = False        # True if any frame flagged nudity
        self.nudityDetail = None      # "CLASS=score,..." from the best nudity frame
        self.bestNudityScore = 0.0    # max class score behind nudityDetail
        self.attrsDirty = False       # attrs materially improved post-report

        _QueuedObjId._idToQueuedObj[idNum] = self

    ###########################################################
    def needsDetection(self, ms=None):
        if not self.reported and \
                self.detectionsRequested < _QueuedObjId._maxDetectionEvents:
            # Hold this object back until its next sample is due, so the
            # budget covers the whole track instead of only its opening
            # seconds.  See _kDetectSpacingMs.  The first _kFastDetectSamples
            # are exempt, and so is the very first sample of all
            # (lastDetectionRequestTime is None), so a subject already present
            # when the track is born is classified exactly as fast as before.
            if self.detectionsRequested >= _kFastDetectSamples and \
                    ms is not None and \
                    self.lastDetectionRequestTime is not None and \
                    ms - self.lastDetectionRequestTime < _kDetectSpacingMs:
                return False
            return True

        # Post-report sampling: person objects stay eligible (throttled) so
        # face/nudity attributes can keep improving; see reportCloudDetection's
        # dirty tracking and _generateFrameReport's update message.
        if _kFaceTrackUpdates and self.reported and \
                self.detectorDecision == 'person' and ms is not None:
            if self.lastDetectionRequestTime is None or \
                    ms - self.lastDetectionRequestTime >= \
                    _kPostReportDetectIntervalMs:
                return True

        return False

    ###########################################################
    def reportSeen(self, ms, logger):
        # logger.debug("SentryID=" + str(self.sentryId) + ": seen at " + str(ms) )
        self.lastSeenBySentry = ms
        self.sentryFramesSeen += 1

    ###########################################################
    def getType(self):
        return self.detectorDecision

    ###########################################################
    def reportCloudDetection(self, ms, type, score, overlap, logger):
        """ Notify the object whenever detection result is received for a particular frame

        Attribute tracking (face name / demographics / nudity) runs for EVERY
        result, including post-vote ones from the throttled post-report
        sampling — a material improvement after the object was reported sets
        attrsDirty so _generateFrameReport sends an attribute-update message.
        Only the type-vote bookkeeping is frozen once a decision is made.
        """
        decisionMade = self.detectorDecision is not None

        # Peel detection attributes off the type before voting.  The detector
        # emits "person:<Name>" for recognized faces and "nudity" as a separate
        # detection on the same object.  If these were left as distinct types
        # they'd fragment the vote (person vs person:Name) or compete with and
        # lose to "person" (nudity).  Instead we record them as attributes and
        # normalize the type back to its clean category for the vote.
        if type == "nudity" or type.startswith("nudity:"):
            # Nudity is an attribute, not a type — record it and don't vote.
            if self.reported and not self.sawNudity:
                self.attrsDirty = True
            self.sawNudity = True
            detail = type.split(":", 1)[1] if ":" in type else ""
            if detail:
                # Keep the detail from the frame with the highest class score.
                maxScore = 0.0
                for part in detail.split(","):
                    if "=" in part:
                        try:
                            maxScore = max(maxScore, float(part.split("=", 1)[1]))
                        except ValueError:
                            pass
                if maxScore >= self.bestNudityScore:
                    if self.reported and \
                            maxScore - self.bestNudityScore >= 0.05:
                        self.attrsDirty = True
                    self.bestNudityScore = maxScore
                    self.nudityDetail = detail
            self.lastDetectionEventTime = ms
            return

        # Peel the "|key=val|..." attribute suffix off the type (present on
        # person/vehicle/animal detections).
        attrs = {}
        if "|" in type:
            type, _, attrStr = type.partition("|")
            for kv in attrStr.split("|"):
                if "=" in kv:
                    k, v = kv.split("=", 1)
                    attrs[k] = v

        # YOLO detection confidence + subtype (best by detection confidence),
        # applies to all detected categories.
        if "dc" in attrs:
            try:
                dc = float(attrs["dc"])
            except ValueError:
                dc = 0.0
            if dc >= self.detConf:
                self.detConf = dc
                if attrs.get("st"):
                    self.subType = attrs["st"]

        if type.startswith("person:") or (type == "person" and attrs):
            name = type.split(":", 1)[1] if ":" in type else ""
            faceConf = 0.0
            if "fc" in attrs:
                try:
                    faceConf = float(attrs["fc"])
                except ValueError:
                    pass

            def _applyDemographics():
                if attrs.get("g"):
                    self.gender = attrs["g"]
                if attrs.get("a"):
                    try:
                        self.age = int(attrs["a"])
                    except ValueError:
                        pass
                if attrs.get("fd"):
                    try:
                        self.faceDetConf = float(attrs["fd"])
                    except ValueError:
                        pass

            if name:
                # Recognized: keep identity + demographics from the best match.
                if faceConf >= self.bestFaceScore:
                    if self.reported and \
                            (name != self.bestFaceName or
                             faceConf - self.bestFaceScore >= 0.05):
                        self.attrsDirty = True
                    self.bestFaceScore = faceConf
                    self.bestFaceName = name
                    _applyDemographics()
            else:
                # Unrecognized face: fill demographics only if we have none yet.
                if self.gender is None and self.age is None:
                    if self.reported and attrs.get("fd") and \
                            self.faceDetConf is None:
                        # First face ever seen on this object (post-report):
                        # "Unknown" face rules need the row updated too.
                        self.attrsDirty = True
                    _applyDemographics()
            type = "person"

        self.lastDetectionEventTime = ms

        if decisionMade:
            # Final type determination had been made — attribute tracking
            # above is all we do; don't touch the vote.
            return

        self.externalDetections[ms].append((type, score, overlap))

    ###########################################################
    def notifyDetectionRequested(self, ms):
        """ Notify we've requested detection for a frame with this object
        """
        self.detectionsRequested += 1
        self.lastDetectionRequestTime = ms

    ###########################################################
    def notifyDetectionCompleted(self, ms):
        """ Notify the object whenever detection attempt occurs for a particular frame
        """
        # max(), not assignment: results can arrive out of order by one.
        # _dropWorkItem publishes its empty result from the PRODUCER thread
        # while run() is still mid-inference on an older item, so a dropped
        # item's result can overtake a real one.  Letting this move backwards
        # makes readyToReport's trackLost test read an object that has in fact
        # settled as "still waiting on the detector" until the next result or
        # the _kForceDecisionTimeout backstop.
        self.lastDetectionResponseTime = max(self.lastDetectionResponseTime, ms)
        if self.detectorDecision is not None:
            # do not update the object if final determination had been made
            return

        self.detectionEventsCount += 1
        if self.lastDetectionEventTime == ms:
            # we've seen a result associated with this ms
            return

        # Make 'unknown' high enough to count, but not so high that it trumps
        # good matches we may see in other frames
        self.externalDetections[ms].append(("unknown", 0.5, 0.5))


    ###########################################################
    def _getScoresForObservedTypes(self):
        """ Returns sum of all scores and overlaps observed for each type across all frame.
            If a type is seen multiple times in a single frame, best object is used to
            represent that frame.
        """
        sumOverlap = defaultdict(float)
        sumScore  = defaultdict(float)
        sumFrames = defaultdict(int)

        # Iterate on all the frames, and pick the best object of each type in each frame
        # Use that objects overlap and score for a decision
        for ms in sorted(self.externalDetections.keys()):
            bestObjectsInFrame = {}
            for type, score, overlap in self.externalDetections[ms]:
                if not type in bestObjectsInFrame:
                    prevObject = (0, 0, 0)
                else:
                    prevObject = bestObjectsInFrame[type]
                if prevObject[0] + prevObject[1] < score + overlap:
                    sumOverlap[type] += ( overlap - prevObject[0] )
                    sumScore[type] += ( score - prevObject[1] )
                    sumFrames[type] += ( 1 - prevObject[2] )
                    bestObjectsInFrame[type] = (overlap, score, 1)

        return sumFrames, sumScore, sumOverlap

    ###########################################################
    def _summarizeScores(self, forceDecision, logger):
        kHighConfidenceScore = 0.9
        kHighConfidenceOverlap = 0.8

        sumFrames, sumScore, sumOverlap = self._getScoresForObservedTypes()
        frameCount = len(list(self.externalDetections.keys()))

        highConfidenceTypes = []
        bestSuperscore = 0
        bestSuperscoreType = None
        bestRealSuperscore = 0
        bestRealType = None
        allTypes = list(sumFrames.keys())

        # See which object types we've seen so far, and if any of those stand out
        for type in allTypes:
            superscore = sumScore[type]+sumOverlap[type]
            if superscore > bestSuperscore:
                bestSuperscore = superscore
                bestSuperscoreType = type
            # Track the best REAL type separately.  "unknown" is an abstention
            # ("we ran the detector and matched nothing"), not evidence, but it
            # is voted like a type -- see notifyDetectionCompleted.  Its
            # superscore therefore grows with every barren frame, so a genuine
            # subject matched on a minority of frames loses to its own absence.
            if type != _kUnknownType and superscore > bestRealSuperscore:
                bestRealSuperscore = superscore
                bestRealType = type
            # Object is considered to be a high-confidence if
            # - it appears in all analyzed frames
            # - its average score and overlap fall within thresholds
            if sumFrames[type] == frameCount and \
                sumScore[type] / float(frameCount) > kHighConfidenceScore and \
                sumOverlap[type] / float(frameCount) > kHighConfidenceOverlap:
                highConfidenceTypes.append(type)

        # Determine if the decision can be made now
        if len(highConfidenceTypes) == 1:
            # Bind the winner to its own name.  'type' out here is whatever the
            # loop above happened to end on, not the type being stored, so
            # reading the stats through it described the wrong object while
            # naming the right one -- and this log is the main diagnostic for
            # why a track classified the way it did.
            chosenType = highConfidenceTypes[0]
            typeFrames = sumFrames[chosenType]
            if typeFrames == 0:
                # Shouldn't be reachable (high confidence requires
                # sumFrames == frameCount, and frameCount == 0 leaves allTypes
                # empty), but the forced-decision branch below guards the same
                # division, so don't trade a misleading log for a crash.
                logger.debug("SentryID=%d detection completed :" \
                            " classifying as %s sentry=%s no frames!" \
                            " typeFrames=0/%d typesSeens=%s" % \
                            (self.sentryId, \
                            chosenType, self.sentryObjType, \
                            frameCount, str(allTypes) ) )
            else:
                avgScore = sumScore[chosenType] / float(typeFrames)
                avgOverlap = sumOverlap[chosenType] / float(typeFrames)
                logger.debug("SentryID=%d detection completed :" \
                            " classifying as %s sentry=%s avgScore=%.2f" \
                            " avgOverlap=%.2f typeFrames=%d/%d typesSeens=%s" % \
                            (self.sentryId, \
                            chosenType, self.sentryObjType, avgScore, \
                             avgOverlap, typeFrames, frameCount, str(allTypes) ) )
            self.detectorDecision = chosenType
        elif len(highConfidenceTypes) != 0 and not forceDecision:
            logger.debug("SentryID=" + str(self.sentryId) + ": " + \
                        " postponing classification; could be one of " + str(highConfidenceTypes) )

        # Force decision if we have to
        if self.detectorDecision is None and forceDecision:
            type = bestSuperscoreType
            # Do not let accumulated "unknown" abstentions outvote a confident
            # real detection.  A subject that enters or leaves frame, or that
            # shares the scene with a bigger mover, is only matched on some of
            # the analysed frames; every other frame adds an "unknown" worth as
            # much as a 0.5 detection.  Measured 2026-08-13 on 09_Jungle
            # 19:04:26 -- YOLO scored the man 0.53-0.91 and the track still
            # stored as "object", alongside three more person-shaped "object"
            # tracks.  Require the real type to average a decent score so a
            # lone marginal hit (the 0.29 "bear" / 0.37 "sheep" this fleet's
            # foliage produces) cannot flip a track on its own.
            if bestSuperscoreType == _kUnknownType and bestRealType is not None:
                realFrames = sumFrames[bestRealType]
                if realFrames > 0 and \
                    sumScore[bestRealType] / float(realFrames) >= _kMinRealTypeScore:
                    logger.debug("SentryID=%d: '%s' avgScore=%.2f over %d/%d "
                                "frames beats accumulated unknown (superscore "
                                "%.2f vs %.2f)" %
                                (self.sentryId, bestRealType,
                                 sumScore[bestRealType] / float(realFrames),
                                 realFrames, frameCount,
                                 bestRealSuperscore, bestSuperscore))
                    type = bestRealType
            typeFrames = sumFrames[type]
            if type == None or typeFrames == 0 or frameCount == 0:
                # This would happen, when Sentry-detected object is so
                # short-lived, that we don't see any full-size frames to
                # run detection on.
                #
                # DEBUG, matching every other outcome branch in this method.  A
                # track can legitimately be 0 ms long, so this can never reach
                # zero and it is not an error; it is one outcome of the vote.
                # At ERROR it was the ONLY member of this family that printed
                # at the deployed INFO level, which made it look like the whole
                # problem instead of ~17% of it -- 1,655 lines in 3.35 h, 10%
                # of one camera's entire log.  It is now counted as noFrames on
                # the periodic CloudStats line alongside the other outcomes,
                # where its share is visible instead of just its volume.
                logger.debug("SentryID=" + str(self.sentryId) + ":" + \
                            "    no frames!." + \
                            " sentry=" + str(self.sentryObjType) + \
                            " frameCount=" + str(frameCount) + \
                            " typesSeen=" + str(allTypes))
                self.detectorDecision = self.sentryObjType
            else:
                # In this case, we've either lost the track or decided we've
                # seen enough (> max frames)
                avgScore = sumScore[type] / float(typeFrames)
                avgOverlap = sumOverlap[type] / float(typeFrames)
                logger.debug("SentryID=%d detection completed :" \
                            " forcing decision to %s sentry=%s avgScore=%.2f" \
                            " avgOverlap=%.2f typeFrames=%d/%d typesSeens=%s" % \
                            (self.sentryId, \
                            type, self.sentryObjType, avgScore, \
                            avgOverlap, typeFrames, frameCount, str(allTypes) ) )
                self.detectorDecision = type


    ###########################################################
    def readyToReport(self, lastFrameProcessedBySentry, logger):
        # Check if this object has been reported at least once
        if self.detectorDecision is not None:
            return True

        # only run summary if have enough detections to go by
        needToCheck = self.detectionEventsCount >= _QueuedObjId._minDetectionEvents

        # max detections ran
        enoughDetecting = self.detectionEventsCount >= _QueuedObjId._maxDetectionEvents

        # The track is lost when:
        # - the tracker has not included this object for _kTrackLostGraceMs
        #   (any absence at all when that is 0)
        # - AND we've never got a chance to ask for a detection
        #   (usually because object livespan is too short to include a non-resized frame)
        # - OR we've received responses to all the detection requests we sent
        missingMs = lastFrameProcessedBySentry - self.lastSeenBySentry
        trackLost = missingMs > 0 and missingMs >= _kTrackLostGraceMs and \
                    ( self.lastDetectionRequestTime is None or \
                    self.lastDetectionResponseTime >= self.lastDetectionRequestTime )
        if trackLost:
            logger.debug("SentryID=" + str(self.sentryId) + ": Track lost - " + \
                        " first=" + str(self.firstSeenBySentry) + \
                        " last=" + str(self.lastSeenBySentry) + \
                        " sentry=" + str(lastFrameProcessedBySentry) + \
                        " events=" + str(self.detectionEventsCount) + \
                        " sentryFrames=" + str(self.sentryFramesSeen) )

        # trackLost is the ONLY exit for an object the detector never decided,
        # and it hinges on the response bookkeeping being complete.  It isn't:
        # a detection result whose frame was already evicted from
        # _trackedObjects notifies nobody (see _processCloudResults), so
        # lastDetectionResponseTime stays permanently behind
        # lastDetectionRequestTime and trackLost can never become True.
        #
        # That object then never decides, and _processDetections' reporting
        # loop breaks on the oldest unready frame -- so ONE of them silences
        # the whole camera forever while it goes on capturing normally.
        # Measured 2026-08-29: 05_Gate_lr held 19fps and non-zero motion blobs
        # for five hours and delivered not one object to the back end; the
        # health view read the frozen progress as "No frames".
        #
        # Time is the backstop the bookkeeping cannot provide.  Once the
        # tracker has moved _kForceDecisionTimeout past this object's last
        # appearance, no further evidence is coming for it, so decide on what
        # we have -- which is exactly what this constant was always for.
        abandoned = (lastFrameProcessedBySentry - self.lastSeenBySentry) > \
                    _kForceDecisionTimeout
        if abandoned and not trackLost:
            logger.warning("SentryID=%d: forcing decision %dms after the last "
                        "sighting; detector still owes us a response "
                        "(requested=%s responded=%s events=%d)" %
                        (self.sentryId,
                         lastFrameProcessedBySentry - self.lastSeenBySentry,
                         str(self.lastDetectionRequestTime),
                         str(self.lastDetectionResponseTime),
                         self.detectionEventsCount))

        if needToCheck or trackLost or abandoned:
            try:
                self._summarizeScores(
                    trackLost or enoughDetecting or abandoned, logger)
            except:
                logger.error("Exception processing scores ... trackLost=%s" \
                            " detectionEventsCount=%d"
                            " detections=%s"
                            " error=%s" %
                            (str(trackLost), self.detectionEventsCount, str(self.externalDetections), traceback.format_exc()))

        return self.detectorDecision is not None
